_target_: qt.models.PointTransformerV3

in_channels: 9
order: ["z", "z-trans", "hilbert", "hilbert-trans"]
stride: [2, 2, 2, 2]
enc_depths: [2, 2, 2, 6, 2]
enc_channels: [32, 64, 128, 256, 512]
enc_num_head: [2, 4, 8, 16, 32]
enc_patch_size: [1024, 1024, 1024, 1024, 1024]
dec_depths: [2, 2, 2, 2]
dec_channels: [64, 64, 128, 256]
dec_num_head: [4, 4, 8, 16]
dec_patch_size: [1024, 1024, 1024, 1024]
mlp_ratio: 4
qkv_bias: true
qk_scale: null
attn_drop: 0.0
proj_drop: 0.0
drop_path: 0.3
shuffle_orders: true
pre_norm: true
enable_rpe: false
enable_flash: false
upcast_attention: false
upcast_softmax: false
cls_mode: true
pdnorm_bn: false
pdnorm_ln: false
pdnorm_decouple: true
pdnorm_adaptive: false
pdnorm_affine: true
pdnorm_conditions: ["ScanNet", "S3DIS", "Structured3D"]