_target_: qt.solvers.Ptv3Solver

lr: 1e-3
weight_decay: 0.01
block_lr_scale: 0.0001

l1_w: 1
rank_w_min: 1
rank_w_max: 3
warmup_start_step: 3000
warmup_steps: 5000
hard_thred: 5
use_margin: true

scheduler_config: 
  type: CosineAnnealingLR
  eta_min: 1e-6
  warm_up: 0.05
  # type: OneCycleLR
  # max_lr: 0.001 #[0.001, 0.0001]
  # pct_start: 0.05
  # anneal_strategy: "cos"
  # div_factor: 10.0
  # final_div_factor: 1000.0