output_dir: logs
seed: 123456
trainer:
  max_epochs: 300
  strategy: ddp
  check_val_every_n_epoch: 4
  log_every_n_steps: 100
  precision: 16-mixed

wandb:
  secret_path: secrets/wandb.yaml
  project: 3dqa

checkpoint:
  save_dir: checkpoints
  save_top_k: 1
  mode: max
