_base_: _train_base
trainer:
  max_epochs: 100
  strategy: ddp
  check_val_every_n_epoch: 4
  log_every_n_steps: 50
  precision: 32 #16-mixed
  accumulate_grad_batches: 2
  detect_anomaly: false

data:
  _base_: data/objaverse_multi_predict4_full

model:
  _base_: model/qt_multi_predict4_full

solver:
  _base_: solver/ptv3_full